"""Fixed-coefficient matrix circuits. No weight ports or weight memories."""
import numpy as np


def csd(w):
    """Canonical signed digit form of an integer: list of (sign, shift) with the fewest
    nonzero digits, e.g. 7 -> [(+1,3), (-1,0)], 45 -> [(+1,6),(-1,4),(-1,2),(+1,0)]."""
    w = int(w)
    digits = []
    i = 0
    while w != 0:
        if w & 1:
            d = 2 - (w & 3)          # 1 -> +1, 3 -> -1
            digits.append((d, i))
            w -= d
        w >>= 1
        i += 1
    return digits[::-1]


def const_array_sv(name, w_kn):
    """K x N weight-stationary array with every weight a constant, one always_ff per
    cell, products written as CSD shift-adds so synthesis never sees a multiplier.
    Same port shape as top.sv minus the weight load; latency K+N-1."""
    w = np.asarray(w_kn, dtype=np.int64)
    k, n = w.shape
    lines = []
    a = lines.append
    a(f"// generated by compiler/compile.py: {k}x{n} hardwired array, {int((w != 0).sum())} nonzero weights")
    a(f"module {name} (")
    a("    input  logic             clk,")
    a("    input  logic             rst_n,")
    a("    input  logic             x_valid,")
    a(f"    input  logic [{k*8-1}:0]  x_vec,")
    a("    output logic             y_valid,")
    a(f"    output logic [{n*32-1}:0] y_vec")
    a(");")
    a(f"    localparam int unsigned LAT = {k + n - 1};")
    a(f"    logic signed [7:0]  xr [{k}][{n+1}];   // xr[i][j] is x_i as seen by cell (i,j); xr[i][0] is the skewed input")
    a(f"    logic signed [31:0] ps [{k+1}][{n}];   // ps[i][j] is the partial sum entering cell (i,j)")
    a("")
    a("    // input skew: row i delayed i cycles")
    for i in range(k):
        if i == 0:
            a(f"    assign xr[0][0] = signed'(x_vec[7:0]);")
        else:
            a(f"    skew #(.W(8), .DELAY({i})) u_skew_{i} (.clk(clk), .rst_n(rst_n), .d(x_vec[{8*i+7}:{8*i}]), .q(xr[{i}][0]));")
    for j in range(n):
        a(f"    assign ps[0][{j}] = 32'sd0;")
    a("")
    a("    always_ff @(posedge clk) begin")
    a("        if (!rst_n) begin")
    a(f"            for (int i = 0; i < {k}; i++) for (int j = 0; j < {n}; j++) begin xr[i][j+1] <= '0; ps[i+1][j] <= '0; end")
    a("        end else begin")
    for i in range(k):
        for j in range(n):
            terms = "".join(
                (" + " if s > 0 else " - ") + (f"(32'(xr[{i}][{j}]) <<< {sh})" if sh else f"32'(xr[{i}][{j}])")
                for s, sh in csd(w[i, j]))
            a(f"            xr[{i}][{j+1}] <= xr[{i}][{j}];  ps[{i+1}][{j}] <= ps[{i}][{j}]{terms};   // w = {int(w[i,j])}")
    a("        end")
    a("    end")
    a("")
    a("    // output deskew: column j delayed N-1-j cycles, valid alongside")
    for j in range(n):
        d = n - 1 - j
        a(f"    skew #(.W(32), .DELAY({d})) u_dsk_{j} (.clk(clk), .rst_n(rst_n), .d(ps[{k}][{j}]), .q(y_vec[{32*j+31}:{32*j}]));")
    a("    skew #(.W(1), .DELAY(LAT)) u_vld (.clk(clk), .rst_n(rst_n), .d(x_valid), .q(y_valid));")
    a("endmodule")
    return "\n".join(lines) + "\n"


def const_wrapper_sv(name, core, k, n, bias):
    """Streaming wrapper (same ports as matvec_rom) around a hardwired core."""
    bias = np.zeros(n, dtype=np.int64) if bias is None else np.asarray(bias, dtype=np.int64)
    lines = []
    a = lines.append
    a(f"// generated by compiler/compile.py: serial in / serial out around {core}")
    a(f"module {name} (")
    a("    input  logic        clk,")
    a("    input  logic        rst_n,")
    a("    input  logic        in_valid,")
    a("    input  logic [7:0]  in_data,")
    a("    output logic        out_valid,")
    a("    output logic [31:0] out_data,")
    a("    output logic        busy")
    a(");")
    a(f"    localparam int unsigned K = {k}, N = {n};")
    a(f"    logic [{k*8-1}:0]  x_vec;")
    a(f"    logic [{n*32-1}:0] y_vec, y_hold;")
    a("    logic x_valid, y_valid;")
    cw = max(k, n).bit_length()
    kw = max(1, (k - 1).bit_length())      # lane index widths for the packed vectors
    nw = max(1, (n - 1).bit_length())
    a(f"    logic [{cw - 1}:0] cnt;        // counts inputs (0..K-1) then outputs (0..N-1)")
    a("    typedef enum logic [1:0] {FILL, RUN, DRAIN} state_t;")
    a("    state_t state;")
    a(f"    {core} u_core (.clk(clk), .rst_n(rst_n), .x_valid(x_valid), .x_vec(x_vec), .y_valid(y_valid), .y_vec(y_vec));")
    a("    localparam logic signed [31:0] BIAS [N] = '{" + ", ".join(f"32'sd{int(v)}" if v >= 0 else f"-32'sd{-int(v)}" for v in bias) + "};")
    a("    assign x_valid = (state == RUN);")
    a("    assign busy = (state != FILL) || (cnt != 0);")
    a("    always_ff @(posedge clk) begin")
    a("        if (!rst_n) begin state <= FILL; cnt <= '0; x_vec <= '0; y_hold <= '0; out_valid <= 1'b0; out_data <= '0; end")
    a("        else begin")
    a("            out_valid <= 1'b0;")
    a("            case (state)")
    a("                FILL: if (in_valid) begin")
    a(f"                    x_vec[8*{kw}'(cnt) +: 8] <= in_data;")
    a(f"                    if (cnt == {cw}'(K-1)) begin cnt <= '0; state <= RUN; end else cnt <= cnt + 1'b1;")
    a("                end")
    a("                RUN: state <= DRAIN;")
    a("                DRAIN: if (y_valid || cnt != 0) begin")
    a("                    // first cycle: latch the whole vector; then one lane per cycle")
    a("                    if (cnt == 0) y_hold <= y_vec;")
    a("                    out_valid <= 1'b1;")
    a(f"                    out_data  <= (cnt == 0 ? signed'(y_vec[31:0]) : signed'(y_hold[32*{nw}'(cnt) +: 32])) + BIAS[{nw}'(cnt)];")
    a(f"                    if (cnt == {cw}'(N-1)) begin cnt <= '0; state <= FILL; end else cnt <= cnt + 1'b1;")
    a("                end")
    a("                default: state <= FILL;")
    a("            endcase")
    a("        end")
    a("    end")
    a("endmodule")
    return "\n".join(lines) + "\n"
